apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  KAFKA_BROKER: "kafka:9092"
  ENV: "production"
  LOG_LEVEL: "info"
